# OmniSci, https://www.omnisci.com/
#
# This is an example file for docker-compose showing
# deployment of OmniSci distributed cluster.
# Doc for installing with Docker: https://www.omnisci.com/docs/latest/4_docker_gpu_ee_recipe.html
# Docs for a distributed cluster: https://www.omnisci.com/docs/latest/4_distributed.html
#
# For making use of GPU, you should use image omnisci/omnisci-ee-cuda:v4.5.0 instead of cpu below.
# 
# All components use the same image, with custom commands.
#
# The leaf nodes create cluster.conf file referencing the sds by ip and port.
# The aggr node creates cluster.conf file referencing the sds and leaves by ip and port.
# The immerse node creates references aggr by ip and port.
#

version: '3'

services:

  sds:
    image: omnisci/omnisci-ee-cpu:v4.5.0
    volumes:
      - v-sds:/omnisci-storage
    command: >
      bash -c "mkdir -p /omnisci-storage/sds ;
      /omnisci/bin/omnisci_sd_server --port 6277 --path /omnisci-storage/sds"
  leaf1:
    image: omnisci/omnisci-ee-cpu:v4.5.0
    volumes:
      - v-leaf1:/omnisci-storage
    command: >
      bash -c "if [ ! -e /omnisci-storage/data ] ; then mkdir -p /omnisci-storage/data ; /omnisci/bin/initdb -f --data /omnisci-storage/data --skip-geo ; fi &&
      echo '[{\"host\": \"sds\", \"port\": 6277, \"role\": \"string\"}]' > /omnisci-storage/cluster.conf &&
      /omnisci/bin/omnisci_server /omnisci-storage/data --config /omnisci-storage/omnisci.conf --string-servers /omnisci-storage/cluster.conf"
# --strings-servers is not a command line option and causes a segfault
  leaf2:
    image: omnisci/omnisci-ee-cpu:v4.5.0
    volumes:
      - v-leaf2:/omnisci-storage
    command: >
      bash -c "if [ ! -e /omnisci-storage/data ] ; then mkdir -p /omnisci-storage/data ; /omnisci/bin/initdb -f --data /omnisci-storage/data --skip-geo ; fi &&
      echo '[{\"host\": \"sds\", \"port\": 6277, \"role\": \"string\"}]' > /omnisci-storage/cluster.conf &&
      /omnisci/bin/omnisci_server /omnisci-storage/data --config /omnisci-storage/omnisci.conf --string-servers /omnisci-storage/cluster.conf"
  aggr:
    image: omnisci/omnisci-ee-cpu:v4.5.0
    ports:
      - "6274:6274"
      - "6278:6278"
    volumes:
      - v-aggr:/omnisci-storage
    command: >
      bash -c "if [ ! -e /omnisci-storage/data ] ; then mkdir -p /omnisci-storage/data ; /omnisci/bin/initdb -f --data /omnisci-storage/data --skip-geo ; fi &&
      echo '[{\"host\": \"sds\", \"port\": 6277, \"role\": \"string\"}, {\"host\": \"leaf1\", \"port\": 6274, \"role\": \"dbleaf\"}, {\"host\": \"leaf2\", \"port\": 6274, \"role\": \"dbleaf\"}]' > /omnisci-storage/cluster.conf &&
      /omnisci/bin/omnisci_server /omnisci-storage/data --config /omnisci-storage/omnisci.conf --cluster /omnisci-storage/cluster.conf"
# --cluster is not a command line option
  immerse:
    image: omnisci/omnisci-ee-cpu:v4.5.0
    ports:
      - "6273:6273"
    command: /omnisci/bin/omnisci_web_server --data /tmp --backend-url "http://aggr:6278"

volumes:
  v-aggr:
  v-leaf1:
  v-leaf2:
  v-sds:

