---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mapd-pv-sds-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: local-ssd
  labels:
    app: mapd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 450Gi
  volumeName: "local-pv-8f5c0c87"

