apiVersion: v1
kind: Service
metadata:
  name: mapd-leaf2
  labels:
    app: mapd-leaf2
spec:
  ports:
    - port: 6277
      name: mapd-leaf2
      protocol: TCP
      targetPort: 6277
  selector:
    app: mapd-leaf2
  clusterIP: None
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mapd-leaf2
  labels:
    app: mapd-leaf2
spec:
  selector:
    matchLabels:
      app: mapd-leaf2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mapd-leaf2
    spec:
      containers:
      - image: docker.io/omnisci/omnisci-ee-cuda:v4.5.0
        imagePullPolicy: IfNotPresent
        name: omnisci-ee-cuda
        env:
        - name: NVIDIA_DRIVER_CAPABILITIES
          value: compute,utility
        - name: NVIDIA_VISIBLE_DEVICES
          value: all
        ports:
        - containerPort: 6277
          name: mapd-leaf2
        resources:
        limits:
          nvidia.com/gpu: 1 # requesting 1 GPU
        volumeMounts:
        - name: mapd-leaf2-persistent-storage
          mountPath: /omnisci-storage
      volumes:
      - name: mapd-leaf2-persistent-storage
        persistentVolumeClaim:
          claimName: ssd-mapd-leaf2
      hostname: omnisci-leaf2
