apiVersion: v1
kind: Service
metadata:
  name: mapd-sds
  labels:
    app: mapd-sds
spec:
  ports:
    - port: 6277
      name: mapd-sds
      protocol: TCP
      targetPort: 6277
  selector:
    app: mapd-sds
  clusterIP: None
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mapd-sds
  labels:
    app: mapd-sds
spec:
  selector:
    matchLabels:
      app: mapd-sds
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mapd-sds
    spec:
      containers:
      - image: docker.io/omnisci/omnisci-ee-cuda:v4.5.0
        imagePullPolicy: IfNotPresent
        name: omnisci-ee-cuda
        command: ["/scripts/start_sds.sh"]
        env:
        - name: NVIDIA_DRIVER_CAPABILITIES
          value: compute,utility
        - name: NVIDIA_VISIBLE_DEVICES
          value: all
        ports:
        - containerPort: 6277
          name: mapd-sds
        resources:
        limits:
          nvidia.com/gpu: 1 # requesting 1 GPU
        volumeMounts:
        - name: mapd-sds-persistent-storage
          mountPath: /omnisci-storage
        - name: wrapper
          mountPath: /scripts
      volumes:
      - name: mapd-sds-persistent-storage
        persistentVolumeClaim:
          claimName: mapd-pv-sds-claim
      - name: wrapper
        configMap:
          name: mapd-cm-sds
          defaultMode: 0755
      hostname: omnisci-sds
