---
- name: Create and attach EBS volume to OmniSci host
  hosts: "{{ hosts_to_apply }}"
  tasks:

    - name: Create GPT label
      parted:
        device: /dev/xvdg
        label: gpt

    - name: Create a new primary partition with a size of 1GiB
      parted:
        device: /dev/xvdg
        number: 1
        state: present

    - name: Create a xfs filesystem on /dev/xvdg1
      filesystem:
        fstype: xfs
        dev: /dev/xvdg1


