kind: ConfigMap
apiVersion: v1
metadata:
  name: heavyai
  namespace: heavyai-dev
data:
  heavy.conf: |-
    port = 6274
    http-port = 6278
    calcite-port = 6279
    data = "/var/lib/heavyai/storage"
    allowed-import-paths = ["/heavyai-storage", "/var/lib/heavyai/storage"]
    read-only = false
    num-gpus = 1

    [web]
    port = 6273
    frontend = "frontend"
    servers-json = "/var/lib/heavyai/servers.json"
  servers.json: |-
    [{
            "database": "heavyai",
            "feature_flags": {
                "ui/enable_brush_filter_edits_from_chart": "true",
                "ui/enable_linked_zoom": "true",
                "ui/enable_map_exports": "true",
                "ui/enable_unrestricted_percentage_view_pie_chart": "true",
                "ui/geojoined-bounding-boxes": "true"
            },
            "immerse_ui_keys": {
                "default": "ALL"
            },
            "host": "heavyai.apps.ocp4.danclark.io",
            "port": 80,
            "protocol": "http",
            "password": "HyperInteractive",
            "username": "admin"
        }
    ]
