---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: heavyai-pv-claim
#  annotations:
#    volume.beta.kubernetes.io/storage-class: local-ssd
  labels:
    app: heavyai
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
#  volumeName: "local-pv-e34c5b90"

