---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlops-efs-pvc
  namespace: heavyai-dev
  labels:
    app: heavyai-agg
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: heavyai-db
  namespace: heavyai-dev
  labels:
    app: heavyai-agg
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi

