---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: heavyai-data
  labels:
    app: heavyai
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: heavydb
  labels:
    app: heavyai
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi

