kind: Deployment
apiVersion: apps/v1
metadata:
  name: heavyai-agg
  namespace: heavyai-dev
  labels:
    app: heavyai-agg
    app.kubernetes.io/part-of: heavyai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heavyai-agg
  template:
    metadata:
      labels:
        app: heavyai-agg
    spec:
      serviceAccount: heavyai
      serviceAccountName: heavyai
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: mlops-efs-pvc
        - name: heavyai
          persistentVolumeClaim:
            claimName: heavyai-db
        - name: config
          configMap:
            name: heavyai
            defaultMode: 420
      containers:
        - resources:
            limits:
              nvidia.com/gpu: '1'
          name: heavyai-agg
          env:
            - name: NVIDIA_DRIVER_CAPABILITIES
              value: 'compute,utility,graphics'
            - name: NVIDIA_VISIBLE_DEVICES
              value: all
#            - name: VK_ICD_FILENAMES
#              value: /etc/vulkan/icd.d/nvidia*
          ports:
            - name: immerse
              containerPort: 6273
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: 6273
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          volumeMounts:
            - name: storage
              mountPath: /heavyai-storage
              subPath: heavyai-storage
            - name: heavyai
              mountPath: /var/lib/heavyai
            - name: config
              mountPath: /var/lib/heavyai/heavy.conf
              subPath: heavy.conf
            - name: config
              mountPath: /var/lib/heavyai/servers.json
              subPath: servers.json
          image: >-
            docker.io/heavyai/heavyai-ee-cuda:latest
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: heavyai-agg
  name: immerse
  namespace: heavyai-dev
spec:
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: immerse
    port: 6273
    protocol: TCP
    targetPort: 6273
  selector:
    app: heavyai-agg
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: heavyai-agg
  name: immerse
  namespace: heavyai-dev
spec:
  host: heavyai.apps.ocp4.danclark.io
  port:
    targetPort: immerse
  to:
    kind: Service
    name: immerse
    weight: 100
  wildcardPolicy: None
